-- Create the table for storing harassment logs
create table harassment_logs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  content text not null,
  category text not null,
  severity text not null,
  reasoning_chain jsonb not null,
  reasoning_chain jsonb not null,
  suggested_action text not null,
  source text default 'Manual'
);

-- Enable Row Level Security (RLS) if needed, or leave open for service role
alter table harassment_logs enable row level security;

-- Create a policy to allow all access (for demo purposes, restrict in production)
create policy "Enable all access for all users" on harassment_logs
for all using (true) with check (true);
